### PR TITLE
Memory Leak Fix

### PR DESCRIPTION
**Pull request by jmabrey**
The previous pull request was closed because the fix introduced another bug that I failed to find. This pull request replaces the previous request.

### CODE REVIEW

**Comment by stain** [comment]
(Sorry for the delay in responding). 

I tried to merged this into [jai-imageio-jpeg2000](https://github.com/stain/jai-imageio-jpeg2000) which now keeps `J2KImageReader` (due to licensing differences) - but then I get a test error:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.544 sec <<< FAILURE!
testname(com.sun.media.imageio.ConverterTest)  Time elapsed: 1.506 sec  <<< ERROR!
java.io.IOException: closed
	at javax.imageio.stream.ImageInputStreamImpl.checkClosed(ImageInputStreamImpl.java:110)
	at javax.imageio.stream.ImageInputStreamImpl.close(ImageInputStreamImpl.java:857)
	at javax.imageio.stream.FileImageInputStream.close(FileImageInputStream.java:151)
	at javax.imageio.ImageIO.read(ImageIO.java:1451)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at com.sun.media.imageio.ConverterTest.testname(ConverterTest.java:27)


Results :

Tests in error: 
  ConverterTest.testname:27 » IO closed
```

See my branch [jmabrey-master](https://github.com/stain/jai-imageio-jpeg2000/tree/jmabrey-master) of jai-imageio-jpeg2000.

Are you able to fix the code or the test to avoid this error? You can raise the pull request again on `jai-imageio-jpeg2000`.

**Comment by stain** [comment]
@jmabrey Have you got a chance to have a look at updating this pull request for [jai-imageio-jpeg2000](https://github.com/jai-imageio/jai-imageio-jpeg2000)? (See above).

If not, I suggest we close this.

**Comment by stain** [comment]
Closed as it breaks the build (and is now in the wrong project) - see jai-imageio/jai-imageio-jpeg2000#2 for further discussion.

**Comment by rleigh-codelibre** [comment]
Reopened as https://github.com/jai-imageio/jai-imageio-jpeg2000/pull/19

**Pull request closed without merging**
